version: "3"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/progress_tracker
    ports:
      - 8000:8000
    image: web:progress_tracker # Name of the Docker image
    container_name: progress_tracker  # Name of the container
    command: python manage.py runserver 0.0.0.0:8000  # Command to run your app
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
     environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db