# Generated by Django 5.1.4 on 2024-12-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
